### PR TITLE
✨Add speaker verification tutorial and documentation

### LINKED ISSUE #99: ✨Add speaker verification notebook and documentation

### PR DESCRIPTION
**Pull request by ibevers**
Add notebook with a speaker verification tutorial. The documentation seemed fine to me, so I left it as is.

### CODE REVIEW

**Comment by fabiocat93** [comment]
hi @ibevers , this is great. do you mind creating a doc.md file introducing speaker verification as a task and linking that doc to the tutorial you created? this would give much more visibility to what you have done. you can use this page as a reference: https://sensein.group/senselab/senselab/audio/tasks/speech_to_text.html

**Comment by fabiocat93** [comment]
@ibevers any update with this?

**Comment by ibevers** [comment]
@fabiocat93 Not for now--please feel free to merge it if it looks okay

**Review by fabiocat93 — APPROVED** [review]
@ibevers thank you

**Pull request merged**
