### PR TITLE
Review and test data-augmentation

### LINKED ISSUE #101: Task: data-augmentation peer review and testing
### Description

Test feedback: 
- Use the global fixtures
- Test could use more descriptive comment

"torch-audiomentations is in a very early development stage, so it's not ready for prime time yet. Meanwhile, star the repo and stay tuned!"
https://pypi.org/project/torch-audiomentations/0.1.0/

### Tasks

Additional tests:
- [x] Test more augmentations for audiomentations
- [x] Test with silence-only audio.
- [x] Test with noise-only audio.
- [x] Test with a combination of augmentations.
- [x] Test an empty audio file and a very short audio file.

### Freeform Notes

_No response_

### PR DESCRIPTION
**Pull request by ibevers**
This PR is for reviewing, updating, and adding tests to the data augmentation task.

### CODE REVIEW

**Comment by ibevers** [comment]
See linked issue for feedback

**Comment by fabiocat93** [comment]
@ibevers i see you self-assigned the review of data augmentation and started working on it. is there anything else that you think should be done in terms of documentation, tutorial, testing, code optimization?

**Comment by ibevers** [comment]
> @ibevers i see you self-assigned the review of data augmentation and started working on it. is there anything else that you think should be done in terms of documentation, tutorial, testing, code optimization?

@fabiocat93 See my suggestion (in the issue) about adding a warning about torch-audiomentations being very early stage.

This task does not have a tutorial.

I don't see any significant problems with the code and documentation. You could add batching under the hood with Pydra when it is run on CPU. Whether we want to use this approach is something we can discuss in biometrics.

To-dos:
- [ ] Consider adding a warning about torch-audiomentations
- [ ] Add tutorial
- [ ] Consider adding CPU batching with Pydra under-the-hood

**Comment by fabiocat93** [comment]
> > @ibevers i see you self-assigned the review of data augmentation and started working on it. is there anything else that you think should be done in terms of documentation, tutorial, testing, code optimization?
> 
> @fabiocat93 See my suggestion (in the issue) about adding a warning about torch-audiomentations being very early stage.
> 
> This task does not have a tutorial.
> 
> I don't see any significant problems with the code and documentation. You could add batching under the hood with Pydra when it is run on CPU. Whether we want to use this approach is something we can discuss in biometrics.
> 
> To-dos:
> 
> * [ ]  Consider adding a warning about torch-audiomentations
> * [ ]  Add tutorial
> * [ ]  Consider adding CPU batching with Pydra under-the-hood

couldn't agree more. Also, We should integrate audiomentations beyond torch-audiomentations. Thank you @ibevers !

**Comment by fabiocat93** [comment]
Hey there,

In this PR, I've tackled the points we discussed and added a few more things:
- Added support for audiomentations (it's slower than torch_audiomentations but offers more types of data augmentation).
- Added a warning in the audio data augmentation docs about torch-audiomentations being incomplete.
- Included a tutorial on audio data augmentation and some docs.
- Fixed bugs in the batch_audios utility.

I also tested using Pydra under the hood, but it caused a lot of issues, so I've commented out those sections for now...

**Pull request merged**
