### PR TITLE
First pr/issue wf

### PR DESCRIPTION
**Pull request by fabiocat93**
trying to increase engagement by greeting people at their first issue and PR. lol

### CODE REVIEW

**Comment by wilke0818** [comment]
can u send a pic of what this would look like?

**Comment by fabiocat93** [comment]
> can u send a pic of what this would look like?

Screenshot 2024-09-26 at 12 25 34 PM

**Review by wilke0818 — APPROVED** [review]
are u sure this won't scare people away?

**Comment by fabiocat93** [comment]
> are u sure this won't scare people away?

that's natural selection

**Pull request merged**
