### PR TITLE
37 task voice activity detection

### LINKED ISSUE #37: Task: Voice activity detection
### Description

Detecting voice in long audio recordings. 

### Tasks

- [ ] Integrate all models for speaker diarization by pyannote.audio accessible through the Huggingface hub.
- [ ] Include torchaudio methods for VAD.

### Freeform Notes

_No response_

### PR DESCRIPTION
**Pull request by ibevers**

### CODE REVIEW

**Comment by fabiocat93** [comment]
@ibevers i have seen that you were considering adding VAD with torchaudio. This is great!

**Comment by ibevers** [comment]
> @ibevers i have seen that you were considering adding VAD with torchaudio. This is great!

Ah, okay, so I should proceed with this then?

**Comment by fabiocat93** [comment]
> > @ibevers i have seen that you were considering adding VAD with torchaudio. This is great!
> 
> Ah, okay, so I should proceed with this then?

That would be great! Thank you @ibevers

**Comment by fabiocat93** [comment]
@ibevers any update with adding VAD using torchaudio?

**Review by fabiocat93 — CHANGES_REQUESTED** [review]
requires adding VAD using torchaudio

**Comment by ibevers** [comment]
This just got pushed down my priority list. I will refine it as soon as I am able

**Comment by fabiocat93** [comment]
@ibevers I have reviewed Torchaudio's documentation, and believe we don't actually want their Vad implementation as part of senselab. They only attempt to trim silence and quiet background sounds from the ends of recordings of speech. They don't create segments for each speech/voice section (which is how we defined voice activity detection).

**Pull request closed without merging**
