### PR TITLE
patch fixes for b2aiprep updates

### LINKED ISSUE #179: Bug: support for Posix paths
### Description

Currently the pydantic model doesn't support `PosixPath` objects.

senselab release 0.18.0

### Steps to Reproduce

```python
from pathlib import Path
wav_path = Path("/some/path/to/wav_file")
Audio.from_filepath(wav_path)
```

### Expected Results

Should load the audio file when referred to by a `Path` object.

### Actual Results

```python
Audio.from_filepath(wav_path)
*** pydantic_core._pydantic_core.ValidationError: 1 validation error for Audio
orig_path_or_id
  Input should be a valid string [type=string_type, input_value=PosixPath('/Users/satra/D...-AD42-69730413F6AB.wav'), input_type=PosixPath]
```

### Additional Notes

Not a significant bug, but given the use of `Path` in various libraries, should be supported.

### PR DESCRIPTION
**Pull request by satra**
I'll keep pushing fixes for b2aiprep.

- closes #179 (allows for posixpaths)
- fixes `plugin_args` for some pydra workflows
- return a tensor to match the annotation

### CODE REVIEW

**Comment by satra** [comment]
@fabiocat93 - before we merge this, we should add `cache` options to the workflows. let me send those changes.

**Comment by fabiocat93** [comment]
@satra I have fixed the last style-related issue and adjusted some returned values to match the annotation

**Review by fabiocat93 — APPROVED** [review]
thank you, @satra looks good to me. it's ready to be merged.

**Comment by satra** [comment]
thanks @fabiocat93 - let me keep this open for a bit longer. i'll hit merge if i don't need any more changes.

**Pull request merged**
