### PR TITLE
Added CHAT file reader

### PR DESCRIPTION
**Pull request by wilke0818**
- Reads and converts .cha files to lists of script lines for use in SenseLab

### CODE REVIEW

**Review by fabiocat93 — APPROVED** [review]
Looks good. Feel free to add unit tests as needed

**Comment by wilke0818** [comment]
we'd need a .cha file for that. not sure what a minimal file might look like. also this currently won't work as I didn't add `pylangacq` to the requirements because as discussed offline, my poetry is currently broken.

**Comment by fabiocat93** [comment]
> we'd need a .cha file for that. not sure what a minimal file might look like. also this currently won't work as I didn't add `pylangacq` to the requirements because as discussed offline, my poetry is currently broken.


- feel free to create a basic .cha file starting from some you find on CHILDES
- I would recommend cloning the repo from scratch. I have tested the installation today and it works for me

**Comment by fabiocat93** [comment]
@wilke0818 have you ever found what was the source of the problem? (and maybe a solution to it)

**Comment by wilke0818** [comment]
I thought you found that the solution was to not use relative paths?

**Comment by fabiocat93** [comment]
> I thought you found that the solution was not to use relative paths?

If this is completed, I will merge it then!

**Pull request merged**
