### PR TITLE
Add audio windowing iterator

### LINKED ISSUE #141: Task: Add Audio Windowing Iterator
### Description

Add iterator object that can be used to iterate over windows in an Audio object.

### Tasks

- [ ] Update Audio datatype to store iterator

### Freeform Notes

Important for b2aiprep

### PR DESCRIPTION
**Pull request by ibevers**
This adds an audio window generator to the Audio class to facilitate feature extraction on audio windows.

### CODE REVIEW

**Comment by fabiocat93** [comment]
@ibevers any updates?

**Comment by ibevers** [comment]
@fabiocat93 I will aim to get this one done by 09/20

**Comment by ibevers** [comment]
@fabiocat93 this is ready for review!🌱 This will be very helpful for Bridge2AI. Thank you in advance!

**Review by fabiocat93 — APPROVED** [review]
looks good to me. looking forward to seeing this used in some workflows!

**Pull request merged**
